// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tphBcVuy6PF2Vmz35tXG42GB9h9VXfE',
    appId: '1:287238800831:web:a3a5ae834b4cdfd2fa4d0a',
    messagingSenderId: '287238800831',
    projectId: 'bblite-98b01',
    authDomain: 'bblite-98b01.firebaseapp.com',
    storageBucket: 'bblite-98b01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkTeSyMJrUNpl1BNbgvQiOF6XO7CFYXz4',
    appId: '1:287238800831:android:c323d7e225544e6bfa4d0a',
    messagingSenderId: '287238800831',
    projectId: 'bblite-98b01',
    storageBucket: 'bblite-98b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNx8o-qch1KBg-9Xsx2ZKIxusuI_xcP08',
    appId: '1:287238800831:ios:7e37fd8d8a62eba9fa4d0a',
    messagingSenderId: '287238800831',
    projectId: 'bblite-98b01',
    storageBucket: 'bblite-98b01.firebasestorage.app',
    iosBundleId: 'com.example.bigbolydeLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNx8o-qch1KBg-9Xsx2ZKIxusuI_xcP08',
    appId: '1:287238800831:ios:7e37fd8d8a62eba9fa4d0a',
    messagingSenderId: '287238800831',
    projectId: 'bblite-98b01',
    storageBucket: 'bblite-98b01.firebasestorage.app',
    iosBundleId: 'com.example.bigbolydeLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tphBcVuy6PF2Vmz35tXG42GB9h9VXfE',
    appId: '1:287238800831:web:e6305622df9018c7fa4d0a',
    messagingSenderId: '287238800831',
    projectId: 'bblite-98b01',
    authDomain: 'bblite-98b01.firebaseapp.com',
    storageBucket: 'bblite-98b01.firebasestorage.app',
  );
}
